export const profileData = {
  name: "Fatin Istiak Polok",
  title: "Flutter Developer",
  bio: "Versatile Flutter Developer with almost 2 years of specialized mobile development experience and 4+ years of business management experience. Skilled in scalable app architecture, API integration, responsive UI/UX, and production releases on the App Store and Google Play. Experienced with Apple and Google Play in-app purchases, RevenueCat, bKash, Stripe, Supabase, Google Maps, Firebase, and TestFlight.",
  email: "fatin15-1944@diu.edu.com",
  phone: "+880 19955 33007",
  location: "Dhaka, Bangladesh",
  cvUrl: "https://drive.google.com/file/d/1BakrTaCyv0gX4NSPtxTaQKgepA-37IIL/view?usp=sharing",
  socialLinks: {
    github: "https://github.com/IstiakPolok",
    linkedin: "https://www.linkedin.com/in/fatin-istiak-polok/",
    portfolio: "http://polok.com",
  },
  stats: [
    { label: "Years Experience", value: "4+" },
    { label: "Completed Projects", value: "20+" },
    { label: "Happy Clients", value: "80+" },
  ],
  languages: [
    { name: "English", level: "Fluent" },
    { name: "Bangla", level: "Native" },
    { name: "Hindi", level: "Conversational" },
  ],
  workExperience: [
    {
      company: "Hook And Took Group",
      position: "Flutter Developer",
      duration: "Apr 2025 – Present",
      description: "Developing Flutter applications with focus on scalable architecture, API integration, and deployment.",
      tags: ["Flutter", "REST API"],
    },
    {
      company: "Flowline Artwork",
      position: "Management Executive",
      duration: "Feb 2022 – Apr 2025",
      description: "Oversaw business operations, workflow optimization, and client/vendor relationship management.",
      tags: ["Operations", "Workflow Management", "Client Relations"],
    },
    {
      company: "Eurobangla Associates Ltd",
      position: "Business Administrator",
      duration: "May 2021 – Feb 2022",
      description: "Managed administrative operations, coordinated teams, and supported project execution.",
      tags: ["Business Management", "Administration"],
    },
  ],
  education: [
    {
      institution: "Daffodil International University, Bangladesh",
      degree: "B.Sc. in Computer Science & Engineering (CSE)",
      duration: "2018 – 2023",
      grade: "CGPA 3.23/4.00",
    },
    {
      institution: "Cambrian College, Dhaka",
      degree: "Higher Secondary Certificate (Science)",
      duration: "2014 – 2016",
      grade: "GPA 4.50/5.00",
    },
    {
      institution: "Monipur High School, Dhaka",
      degree: "Secondary School Certificate (Science)",
      duration: "2004 – 2014",
      grade: "GPA 4.41/5.00",
    },
  ],
  skills: {
    Languages: ["Dart", "Python", "SQL", "JavaScript"],
    Frameworks: ["Flutter", "FastAPI", "Flask", "WordPress"],
    Backend: ["REST APIs", "API Integration"],
    Databases: ["Firebase", "Supabase", "SQL Databases"],
    DevOps: ["Git", "Docker"],
    Cloud: ["Microsoft Azure"],
    Design: ["UI/UX Design", "Graphic Design"],
  },
  projects: [
    {
      name: "TrustTaste AI",
      subtitle: "Restaurant Management App",
      description: "AI voice agent handles calls, reservations, and orders with staff transfer and React dashboard sync. SQA phase – planned App Store & Play release.",
      technologies: "Flutter, Twilio, AI, Firebase",
      links: [
        { label: "Download APK", url: "#" },
      ],
    },
    {
      name: "Goliaths",
      subtitle: "Self-Growth and Donation App",
      description: "Self-growth platform with Stripe donations, AI mental health chatbot, motivational quotes, and subscription management. Live on Google Play.",
      technologies: "Flutter, Stripe, AI, Firebase",
      links: [
        { label: "Google Play", url: "#" },
      ],
    },
    {
      name: "Qurany",
      subtitle: "AI-Powered Quranic Companion",
      description: "Quranic app with AI spiritual guidance, voice interaction, prayer alerts, and RevenueCat subscriptions. SQA phase – upcoming App Store & Play release.",
      technologies: "Flutter, GetX, RevenueCat, AI (STT/TTS), Firebase",
      links: [
        { label: "TestFlight (Beta)", url: "#" },
      ],
      images: [
        new URL("./assets/project/qurani/1.jpg", import.meta.url).href,
        new URL("./assets/project/qurani/2.jpg", import.meta.url).href,
        new URL("./assets/project/qurani/3.jpg", import.meta.url).href,
        new URL("./assets/project/qurani/4.jpg", import.meta.url).href,
        new URL("./assets/project/qurani/5.jpg", import.meta.url).href,
        new URL("./assets/project/qurani/6.jpg", import.meta.url).href,
        new URL("./assets/project/qurani/7.jpg", import.meta.url).href,
        new URL("./assets/project/qurani/8.jpg", import.meta.url).href,
        new URL("./assets/project/qurani/9.jpg", import.meta.url).href,
        new URL("./assets/project/qurani/10.jpg", import.meta.url).href,
      ],
    },
    {
      name: "CircleSlate",
      subtitle: "iOS Deployment",
      description: "Handled App Store submission, provisioning profiles, signing certificates, TestFlight distribution, and production release.",
      technologies: "App Store Connect, TestFlight",
      links: [
        { label: "App Store", url: "#" },
      ],
    },
    {
      name: "Chatter Matters",
      subtitle: "iOS & Android Deployment",
      description: "Managed full deployment on both App Store and Google Play including store compliance, build signing, and production rollout.",
      technologies: "App Store Connect, Google Play Console",
      links: [
        { label: "App Store", url: "#" },
        { label: "Google Play", url: "#" },
      ],
    },
  ],
};
